// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpbjwvhgvhdlsdzotxif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwYmp3dmhndmhkbHNkem90eGlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NzA0MDYsImV4cCI6MjA3MjI0NjQwNn0.UIl5cvmwh1bBuV-CCGoYPok_A0bwOG6iD8DMnibLOlo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});